spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      discovery:
        service-id: config-server

server:
  port: 8088

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
