spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
        - id: profile-service
          uri: lb://profile-service
          predicates:
            - Path=/profile/**
        - id: game-service
          uri: lb://game-service
          predicates:
            - Path=/game/**, /win-go/**
        - id: transaction-service
          uri: lb://transaction-service
          predicates:
            - Path=/transaction/**
        - id: referral-service
          uri: lb://referral-service
          predicates:
            - Path=/referral/**

server:
  port: 8060

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}

management:
  tracing:
    sampling:
      probability: 1.0