spring:
  config:
    import: file:config-server/src/main/resources/config/secrets.properties
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5431/superwin-dev-v1
    # ?currentSchema=game_service
    #  Just for test purpose. Not safe for prod
    #  Do this if you want to lose you job and get laughed on
    username: postgres
    password: superwin
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true

server:
  port: 8094

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}

# This helps in publishing 100% of matrices to zipkin
# probability : 1.0
management:
  tracing:
    sampling:
      probability: 1.0